### ISSUE TITLE
Save highscores

### ISSUE THREAD

**Issue by gaetanmaisse** [cycle-game/Cycle#18]
Players scores should be saved in order to be able to create a "Top X" score/player according to the level they used to play.

Maybe Cloud FireStore or Realtime Database can be good solutions to save data for free: https://firebase.google.com/products

**Comment by ThibaudAV** [comment]
#35 
I just had 10 minutes of fun with firebase :p 

I just started firebase hosting :
https://cycle-3677e.web.app/
