### ISSUE TITLE
Select a theming library

### ISSUE THREAD

**Issue by gaetanmaisse** [cycle-game/Cycle#52]
As a major part of Cycle will be done with React it could be great to use a component library to simplify the design. Here are some of the most popular ones: 
 - https://material-ui.com
 - https://react-bootstrap.github.io
 - https://v2.grommet.io
 - https://ant.design/docs/react/introduce
 - https://blueprintjs.com/

material-ui looks to be the most complete, followed and evolving one.

What is your opinion about this?

**Comment by Remi-p** [comment]
Some comparisons/listing:
https://hackernoon.com/the-coolest-react-ui-frameworks-for-your-new-react-app-ad699fffd651
https://www.npmtrends.com/@blueprintjs/core-vs-ant-design-pro-vs-blueprint-vs-grommet-vs-material-ui-vs-react-bootstrap-vs-reactstrap
https://www.reddit.com/r/javascript/comments/7qrcas/what_is_you_favorite_ui_framework_for_react/
https://blog.bitsrc.io/11-react-component-libraries-you-should-know-178eb1dd6aa4?gi=a4649a29353e

**Comment by jgiovaresco** [comment]
I don't care. I have faith in you 💋
