### ISSUE TITLE
Editor & Levels after 8 included are broken since the Phaser 2.5.0 update

### ISSUE THREAD

**Issue by jgiovaresco** [cycle-game/Cycle#6]
Since I don't know the level 8 is broken

![Screenshot 2019-06-26 at 18 02 16](https://user-images.githubusercontent.com/4171593/60196158-cf9ad000-983c-11e9-9636-6d4bf2251889.png)

![Jun-26-2019 18-09-42](https://user-images.githubusercontent.com/4171593/60196540-acbceb80-983d-11e9-83f6-89111ab8cc26.gif)

**Comment by Remi-p** [comment]
💡 On Firefox `67.0.4` (_64-bit_) from https://cycle-game.github.io/Cycle/, the level doesn't seem to be impacted by the bug

---

Also, it's the first level to have sprites more than 8 units from the planet:
https://github.com/cycle-game/Cycle/blob/85d009b9992760d9bc0cc1f2402f58fb0c9194af/src/Etats/levels.ts#L281
Maybe resizing is broken
https://github.com/cycle-game/Cycle/blob/85d009b9992760d9bc0cc1f2402f58fb0c9194af/src/Etats/play.ts#L295-L303

https://github.com/cycle-game/Cycle/blob/85d009b9992760d9bc0cc1f2402f58fb0c9194af/src/variables.ts#L1

**Comment by jgiovaresco** [comment]
Indeed, even on Chrome with https://cycle-game.github.io/Cycle/ everything is fine. I suspect https://github.com/cycle-game/Cycle/commit/0a23c0c6ecc0504b91b4c8ca98b8d78b4d577e52 🤔

**Comment by jgiovaresco** [comment]
I confirm the bump to 2.5.0 of Phaser has introduced the issue

**Comment by gaetanmaisse** [comment]
I tried with `phaser-ce@2.13.2` and this bug is fixed BUT there is a new one in dude height: it is colliding with some platforms 🙃

**Comment by jgiovaresco** [comment]
> I tried with `phaser-ce@2.13.2` and this bug is fixed BUT there is a new one in dude height: it is colliding with some platforms 🙃

Maybe it will be easier to debug this 🤷‍♂

**Comment by Remi-p** [comment]
Closed by #22.
Editor issue has been splitted to #24.
